language: node_js

node_js:
- 9.11.1

before_install:
- npm i -g yarn@latest

cache:
  directories:
  - node_modules

script:
- yarn lint
- yarn test

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: i8TTwL6GWODNvJqm/wjWLV4+NlCkx1ObHDCap0l43F6fjhyBUgN9Kuv8zLJ9cvwJag7PEwg91tqbdxTFyMknaKnmIwAH/g8eVD1wlWx3XSfuWRgQeslqG5SKoXVLS93bosCpHqiZjd7R/MfSgsTFXp6gnyteqPJqcZpCQBYILUWUA28XQeHCs1UNJRUqFTe/r9n9dcbr7WVmAGQXGOu8dGWAo+xXiKsea4JzMyuRgUow3uP+YR5NnLsJ/rEgUkhlVNRq56d58Dm54/jpAunzYsNouYWoRH4ijSyAHyfhxHlvHrH/Rucc6Ms+lG07LN58h+x1SAQINlO1HDRLpDZvaup5ZHRB3TIZypibEzHp4ieVfEuegF9AmrPUwZLKuEMX175hBgXP783LgWBLyT+hG28zqRMEKoKxyN/jwvV8PSQkPRnvKYpWUNSzsa6JnuyBWAgbG1TVljtJaEazK9HRdCx3JgORmWoFuTdYaDhVGuAORFMSPkDRglE0/6R21r4BR+l18oycagItNhJnMsTSAI+D/Fr4tZjYabqvvDh5pQSDynDKFNvGe6myXARD6IG/iFVl9ljkbVWK3daRwhJsP8MPwD0J7qGfJZvo23kwLh3PY4e91KafXRXCvMniu8XjC9nLEIuTbVbVvCNJnR0TjGI8m199cOk+fbhTbBoS99E=
  app: poke-viewer-graphql-service


